---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/demaconsulting/NuGetInstaller
    about: Read the documentation for NuGetInstaller
  - name: 💬 Discussions
    url: https://github.com/demaconsulting/NuGetInstaller/discussions
    about: Ask questions and discuss with the community
